version: '3.9'

services:
  api:
    command: >
      sh -c "npm run test:e2e"
    container_name: cont_api_app_test
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=app_test_user
      - DATABASE_PASSWORD=app_test_password
      - DATABASE_NAME=app_test_DB
      - DATABASE_SYNC=true
      - JWT_SECRET=th-2026%notif_/dev$$

  postgres:
    image: postgres:16
    container_name: cont_postgres_app_test  
    ports:
      - '5433:5432'  
    environment:
      POSTGRES_USER: app_test_user
      POSTGRES_PASSWORD: app_test_password 
      POSTGRES_DB: app_test_DB
